<%@ Page Language="VB" MasterPageFile="~/Master/IlluminMasterPage.master" AutoEventWireup="false" CodeFile="UserQuery.aspx.vb" Inherits="UserQuery" %>

<asp:Content ID="ChildPageHead" ContentPlaceHolderID="head" runat="server">
    <title>User Query</title>
    <link href="../css/style.css" rel="stylesheet" type="text/css" />
    <script src="../js/validation.js" type="text/javascript"></script>
    <script src="../js/operation.js" type="text/javascript"></script>
    <telerik:RadStyleSheetManager ID="RadStyleSheetManager1" runat="server" />
    <script type="text/javascript">
        //this method is used to open add user page.
        function OpenAddUserPage() {
            var randomStr = getRandom()
            var addResult = window.showModalDialog("User.aspx?OperateType=New&i=" + randomStr, window, 'dialogWidth=800px;dialogHeight=600px;center:yes');
            if (addResult == 'success') {
                //refresh the grid,please take care of the control name, maybe not btnQuery.
                $("input[id$='btnQuery']").click();
            }
        }
        //this method is used to open modify page.
        function OpenModifyPage(id) {
            var randomStr = getRandom() 
            var addResult = window.showModalDialog("User.aspx?OperateType=Modify&id=" + id + "&i=" + randomStr, window, 'dialogWidth=800px;dialogHeight=600px');
            if (addResult == 'success') {
                //refresh the grid,please take care of the control name, maybe not btnQuery.
                $("input[id$='btnQuery']").click();
            }
        }

        //this method is used to open assign role page.
        function OpenAssignRolePage(id) {
            var randomStr = getRandom()
            var result = window.showModalDialog("AssignRoleToUser.aspx?OperateType=New&id=" + id + "&i=" + randomStr, window, 'dialogWidth=800px;dialogHeight=600px;center:yes');
        }
    </script>
</asp:Content>

<asp:Content ID="ChildPageBody" ContentPlaceHolderID="PageContentPlaceHolder" runat="server">
    <form id="form1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
        <Scripts>
            <%--Needed for JavaScript IntelliSense in VS2010--%>
            <%--For VS2008 replace RadScriptManager with ScriptManager--%>
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js" />
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js" />
            <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js" />
        </Scripts>
    </telerik:RadScriptManager>
    <script type="text/javascript">
        //Put your JavaScript code here.
    </script>
    <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
    </telerik:RadAjaxManager>
    <div class="title">
        User Query
    </div>
    <table width="100%" class="query" id="table1">
        <caption class="advover" onclick="adv(table1,main)">
            Query</caption>
        <tbody id="main">
            <tr>
                <td width="15%">
                    Name
                </td>
                <td width="35%">
                    <asp:TextBox ID="txtName" runat="server" CssClass="text"></asp:TextBox>
                </td>
                <td width="15%">
                    Position</td>
                <td width="35%">
                    <asp:DropDownList ID="ddlPosition" runat="server">
                    </asp:DropDownList>
                </td>
            </tr>
            <tr class="dgf">
                <td colspan="4">
                    <asp:Button ID="btnQuery" runat="server" CssClass="btnqry" Text="Query" />
                    &nbsp;<input type="reset" name="Submit2" value="Clear Condition" onclick="ClearCondition();" class="btnreset" />
                    &nbsp;<input type="button" name="btnAdd" value="Add User" class="btnadd" onclick="javascript:OpenAddUserPage()" />
                </td>
            </tr>
        </tbody>
    </table>
    <div class="queryresultgrid">
        <telerik:RadGrid ID="gridResult" runat="server" AllowPaging="True" 
            AllowSorting="True" PageSize="2" AutoGenerateColumns="False" 
            GridLines="None" AutoGenerateDeleteColumn="True" CellSpacing="0" 
            Width="100%" Height ="450px">
            <ClientSettings AllowColumnsReorder="True" ReorderColumnsOnClient="True">
                <Selecting AllowRowSelect="True" />
                <Scrolling AllowScroll="True" UseStaticHeaders="True" />
                
            </ClientSettings>
            <MasterTableView PageSize="15">
                <CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>
                <RowIndicatorColumn>
                    <HeaderStyle Width="20px"></HeaderStyle>
                </RowIndicatorColumn>
               
                <ExpandCollapseColumn>
                    <HeaderStyle Width="20px"></HeaderStyle>
                </ExpandCollapseColumn>
                <Columns>                   
                    <telerik:GridBoundColumn DataField="Code"  HeaderText="Code" UniqueName="codeColumn">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="E_Name" HeaderText="E_Name" UniqueName="enameColumn">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="C_Name" HeaderText="C_Name" UniqueName="cnameColumn">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Email" HeaderText="Email" UniqueName="emailColumn">
                    <HeaderStyle Width="80px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Department" HeaderText="Department" 
                        UniqueName="departmentColumn" Visible="False">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="City" HeaderText="City" 
                        UniqueName="cityColumn" Visible="False">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Position" HeaderText="Position" UniqueName="positionColumn">
                    <HeaderStyle Width="50px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="managerename" HeaderText="Line Manage" UniqueName="lineManageColumn">
                    <HeaderStyle Width="40px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="ID" Display="False" HeaderText="ID" UniqueName="IDColumn">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn HeaderText="Edit" UniqueName="editColumn">
                    <HeaderStyle Width="20px" />
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn HeaderText="Assign Role" UniqueName="roleColumn">
                     <HeaderStyle Width="20px" />
                    </telerik:GridBoundColumn>
                </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
                <PagerStyle Mode="NumericPages" />
            </MasterTableView>

<FilterMenu EnableImageSprites="False">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</HeaderContextMenu>
        </telerik:RadGrid>
    </div>
    
    </form>
</asp:Content>
