<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ProjectKeyDocUpload.aspx.vb" Inherits="PMS_ProjectKeyDocUpload" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Key Document Upload</title>
 <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <base target="_self" />
    <script src="../js/operation.js" type="text/javascript"></script>
    <link href="../css/style.css" rel="stylesheet" type="text/css" />
 
        <style id="Style1" type="text/css" runat="server">
            .radupload { float: left; margin-bottom:20px; }
            .bigModule { clear: both; }
            .smallModule { margin-bottom:20px; }
            #controlContainer { vertical-align: top; padding: 20px 10px; }
            .ruProgressArea { position: absolute; top: 0; left: 10px; }
            input.RadUploadSubmit { margin-top: 20px; }
        </style>
      
    
       
</head>
	
<body  >
        <form id="form1" runat="server" >

        
         
             <table cellspacing="1" cellpadding="1" class="info" >
              <tbody>
               
                <tr >
                    <td class ="title" colspan="4">
                        Key Document Upload</td>
                </tr>
               
                <tr>
                    <td class="lable" style="width: 210px">
                        Job Numer:</td>
                    <td    >
                        <telerik:RadTextBox ID="txtJobNumber" Runat="server" Skin="Windows7" 
                            Width="200px" Rows="1">
                        </telerik:RadTextBox>
                    </td>
                    <td class="lable">
                        Jab Name:</td>
                    <td  >
                        <telerik:RadTextBox ID="txtJobName" Runat="server" Skin="Windows7" 
                            Width="200px" Rows="1">
                        </telerik:RadTextBox>
                    </td>
                </tr>
                <tr>
                    <td class="lable" style="width: 210px">
                        Client:</td>
                    <td colspan="3"    >
                
                        <telerik:RadTextBox ID="txtClient" Runat="server" Skin="Windows7" 
                    Width="520px" Rows="1">
                        </telerik:RadTextBox>
                
                    </td>
                </tr>
                <tr>
                    <td class="lable" colspan="4">
                        &nbsp;</td>
                </tr>
            
                <tr>
                    <td class="lable" style="width: 210px">
                        File Type:</td>
                    <td colspan="3"    >

     

                        <telerik:RadComboBox ID="cbFileType" Runat="server" Width="200px" 
                            AutoPostBack="True">
                        </telerik:RadComboBox>

                    </td>
                </tr>
            
                <tr>
                    <td class="lable" style="width: 210px">
                        File Upload:</td>
                    <td colspan="3"    >

     

                        <telerik:RadUpload ID="RadUpload" Runat="server" 
                            TargetFolder="../Contract/">
                        </telerik:RadUpload>
                       
                        <telerik:RadGrid ID="RadGrid" runat="server" AutoGenerateColumns="False" 
                            AutoGenerateDeleteColumn="True" CellSpacing="0" GridLines="None">
<MasterTableView>
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="Id" 
            FilterControlAltText="Filter columnId column" HeaderText="Id" 
            UniqueName="columnId" Visible="False">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="ProId" 
            FilterControlAltText="Filter columnProId column" HeaderText="ProId" 
            UniqueName="columnProId" Visible="False">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="FileName" 
            FilterControlAltText="Filter columnFileName column" HeaderText="File Name" 
            UniqueName="columnFileName">
            <HeaderStyle Width="150px" />
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="FileFolder" 
            FilterControlAltText="Filter columnFileFolder column" HeaderText="File Folder" 
            UniqueName="columnFileFolder" Visible="False">
            <HeaderStyle Width="50px" />
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="FileType" 
            FilterControlAltText="Filter columnFileType column" HeaderText="FileType" 
            UniqueName="columnFileType">
            <HeaderStyle Width="80px" />
        </telerik:GridBoundColumn>
        <telerik:GridButtonColumn CommandName="Download" 
            FilterControlAltText="Filter columnDownload column" Text="Download" 
            UniqueName="columnDownload">
        </telerik:GridButtonColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</HeaderContextMenu>
                        </telerik:RadGrid>

                    </td>
                </tr>
                <tr>
                    <td colspan="4" align="center" style =" height:28px;">

                       <div style="text-align: center ">
                        <telerik:RadButton ID="btnSave" runat="server"  Text ="Save" Font-Names="Arial" 
                            Font-Size="9pt" Width="120px" Skin="Hay"  >

                             <Icon PrimaryIconUrl="../images/Save.png" PrimaryIconLeft="10" PrimaryIconTop="4" />
                        </telerik:RadButton>
                
                            </div>
                       
                        </td>
                </tr>
                </tbody>
            </table>
            <div >
               <table cellspacing="1" cellpadding="1"  class="button">
                <tbody>
                </tbody>
              </table>
                
                <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
                </telerik:RadScriptManager>
                
             
                
                <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server">
                    <AjaxSettings>
                        <telerik:AjaxSetting AjaxControlID="cbFileType">
                            <UpdatedControls>
                                <telerik:AjaxUpdatedControl ControlID="RadUpload" />
                            </UpdatedControls>
                        </telerik:AjaxSetting>
                    </AjaxSettings>
                </telerik:RadAjaxManager>
                
             
                
            </div>     


            
             
              

             
        
                
      
         </form>
 
</body>
</html>
