'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class Base_MessageReceiver
        
        Private _id As Integer
        
        Private _message_id As Integer
        
        Private _message_receiver_id As Integer
        
        Private _message_receiver_name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of id
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me._id = value
            End Set
        End Property
        
        'This is the property of message_id
        Public Property message_id() As Integer
            Get
                Return Me._message_id
            End Get
            Set
                Me._message_id = value
            End Set
        End Property
        
        'This is the property of message_receiver_id
        Public Property message_receiver_id() As Integer
            Get
                Return Me._message_receiver_id
            End Get
            Set
                Me._message_receiver_id = value
            End Set
        End Property
        
        'This is the property of message_receiver_name
        Public Property message_receiver_name() As String
            Get
                Return Me._message_receiver_name
            End Get
            Set
                Me._message_receiver_name = value
            End Set
        End Property
    End Class
End Namespace
