'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class PMS_ProjectRevenue
        
        Private _Id As Integer
        
        Private _ProjectId As Integer
        
        Private _JobNumber As String
        
        Private _CostName As String
        
        Private _CostValue As Decimal
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of Id
        <ColumnMapping("Id")>  _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me._Id = value
            End Set
        End Property
        
        'This is the property of ProjectId
        <ColumnMapping("ProjectId")>  _
        Public Property ProjectId() As Integer
            Get
                Return Me._ProjectId
            End Get
            Set
                Me._ProjectId = value
            End Set
        End Property
        
        'This is the property of JobNumber
        <ColumnMapping("JobNumber")>  _
        Public Property JobNumber() As String
            Get
                Return Me._JobNumber
            End Get
            Set
                Me._JobNumber = value
            End Set
        End Property
        
        'This is the property of CostName
        <ColumnMapping("CostName")>  _
        Public Property CostName() As String
            Get
                Return Me._CostName
            End Get
            Set
                Me._CostName = value
            End Set
        End Property
        
        'This is the property of CostValue
        <ColumnMapping("CostValue")>  _
        Public Property CostValue() As Decimal
            Get
                Return Me._CostValue
            End Get
            Set
                Me._CostValue = value
            End Set
        End Property
    End Class
End Namespace
