'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    Public Enum TaskStatus
        Active
        Deleted
    End Enum
    Public Enum TaskType
        OptionalTask
        RequiredTask
        SelfDefinedTask
    End Enum
    <System.SerializableAttribute()> _
    Public Class PMS_Component

        Private _id As Integer

        Private _StageId As Integer

        Private _KeyWords As String

        Private _ComponentName As String

        Private _SampleDesign As String

        Private _SampleSize As String

        Private _MethdologyType As Integer

        Private _Methodology As Integer
        Private _CreatedBy As Integer

        Private _CreatedDate As Date

        Private _UpdatedBy As Integer

        Private _UpdatedDate As Date

        Private _Jobnumber As String

        Public Sub New()
            MyBase.New()
        End Sub

        'This is the property of id
        <ColumnMapping("id")> _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set(ByVal value As Integer)
                Me._id = value
            End Set
        End Property

        'This is the property of StageId
        <ColumnMapping("StageId")> _
        Public Property StageId() As Integer
            Get
                Return Me._StageId
            End Get
            Set(ByVal value As Integer)
                Me._StageId = value
            End Set
        End Property

        'This is the property of KeyWords
        <ColumnMapping("KeyWords")> _
        Public Property KeyWords() As String
            Get
                Return Me._KeyWords
            End Get
            Set(ByVal value As String)
                Me._KeyWords = value
            End Set
        End Property


        'This is the property of ComponentName
        <ColumnMapping("ComponentName")> _
        Public Property ComponentName() As String
            Get
                Return Me._ComponentName
            End Get
            Set(ByVal value As String)
                Me._ComponentName = value
            End Set
        End Property

        'This is the property of SampleDesign
        <ColumnMapping("SampleDesign")> _
        Public Property SampleDesign() As String
            Get
                Return Me._SampleDesign
            End Get
            Set(ByVal value As String)
                Me._SampleDesign = value
            End Set
        End Property

        'This is the property of SampleSize
        <ColumnMapping("SampleSize")> _
        Public Property SampleSize() As String
            Get
                Return Me._SampleSize
            End Get
            Set(ByVal value As String)
                Me._SampleSize = value
            End Set
        End Property

        'This is the property of MethdologyType
        <ColumnMapping("MethdologyType")> _
        Public Property MethdologyType() As Integer
            Get
                Return Me._MethdologyType
            End Get
            Set(ByVal value As Integer)
                Me._MethdologyType = value
            End Set
        End Property

        'This is the property of Methodology
        <ColumnMapping("Methodology")> _
        Public Property Methodology() As Integer
            Get
                Return Me._Methodology
            End Get
            Set(ByVal value As Integer)
                Me._Methodology = value
            End Set
        End Property

        'This is the property of CreatedBy
        <ColumnMapping("CreatedBy")> _
        Public Property CreatedBy() As Integer
            Get
                Return Me._CreatedBy
            End Get
            Set(ByVal value As Integer)
                Me._CreatedBy = value
            End Set
        End Property

        'This is the property of CreatedDate
        <ColumnMapping("CreatedDate")> _
        Public Property CreatedDate() As Date
            Get
                Return Me._CreatedDate
            End Get
            Set(ByVal value As Date)
                Me._CreatedDate = value
            End Set
        End Property

        'This is the property of UpdatedBy
        <ColumnMapping("UpdatedBy")> _
        Public Property UpdatedBy() As Integer
            Get
                Return Me._UpdatedBy
            End Get
            Set(ByVal value As Integer)
                Me._UpdatedBy = value
            End Set
        End Property

        'This is the property of UpdatedDate
        <ColumnMapping("UpdatedDate")> _
        Public Property UpdatedDate() As Date
            Get
                Return Me._UpdatedDate
            End Get
            Set(ByVal value As Date)
                Me._UpdatedDate = value
            End Set
        End Property



        Private _CityCovergyList As New List(Of PMS_CityCoverage)
        Public Property CityCovergyList As List(Of PMS_CityCoverage)
            Get
                Return _CityCovergyList
            End Get
            Set(ByVal value As List(Of PMS_CityCoverage))
                _CityCovergyList = value
            End Set
        End Property
        Private _CriteriaList As New List(Of PMS_RespondentCriteria)
        Public Property CriteriaList As List(Of PMS_RespondentCriteria)
            Get
                Return _CriteriaList
            End Get
            Set(ByVal value As List(Of PMS_RespondentCriteria))
                _CriteriaList = value
            End Set
        End Property
        Private _methodologyDescription As String
        Public Property MethodologyDescription As String
            Get
                Return _methodologyDescription
            End Get
            Set(ByVal value As String)
                _methodologyDescription = value
            End Set
        End Property
        Private _proposalId As Integer
        Public Property ProposalId As Integer
            Get
                Return _proposalId
            End Get
            Set(ByVal value As Integer)
                _proposalId = value
            End Set
        End Property

        'added manually
        'This is the property of MethodologyTypaName
        Private _MethodologyTypaName As String
        <ColumnMapping("MethodologyTypaName")> _
        Public Property MethodologyTypaName() As String
            Get
                Return Me._MethodologyTypaName
            End Get
            Set(ByVal value As String)
                Me._MethodologyTypaName = value
            End Set
        End Property

        Private _MethodologyName As String
        <ColumnMapping("MethodologyName")> _
        Public Property MethodologyName() As String
            Get
                Return Me._MethodologyName
            End Get
            Set(ByVal value As String)
                Me._MethodologyName = value
            End Set
        End Property

        'This is the property of Jobnumber
        <ColumnMapping("Jobnumber")> _
        Public Property Jobnumber() As String
            Get
                Return Me._Jobnumber
            End Get
            Set(ByVal value As String)
                Me._Jobnumber = value
            End Set
        End Property

        Private _TimingTaskList As New List(Of PMS_Timing)
        ''' <summary>
        ''' Task list for timing
        ''' </summary>
        ''' <value></value>
        ''' <returns></returns>
        ''' <remarks></remarks>
        Public Property TimingTaskList As List(Of PMS_Timing)
            Get
                Return _TimingTaskList
            End Get
            Set(ByVal value As List(Of PMS_Timing))
                _TimingTaskList = value
            End Set
        End Property
        Private _QuotationList As New List(Of PMS_Quotation)
        ''' <summary>
        ''' task list for quotation
        ''' </summary>
        ''' <value></value>
        ''' <returns></returns>
        ''' <remarks></remarks>
        Public Property QuotationTaskList As List(Of PMS_Quotation)
            Get
                Return _QuotationList
            End Get
            Set(ByVal value As List(Of PMS_Quotation))
                _QuotationList = value
            End Set
        End Property
        Private _ComponentCostingFile As PMS_ComponentCostingFile
        ''' <summary>
        ''' This is the consting file of component
        ''' </summary>
        ''' <value></value>
        ''' <returns></returns>
        ''' <remarks></remarks>
        Public Property ComponentCostingFile As PMS_ComponentCostingFile
            Get
                Return _ComponentCostingFile
            End Get
            Set(ByVal value As PMS_ComponentCostingFile)
                _ComponentCostingFile = value
            End Set
        End Property
    End Class
End Namespace
