'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class PMS_Methodology
        
        Private _id As Integer
        
        Private _ComponentId As Integer
        
        Private _MethodologyTypeId As Integer
        
        Private _MethodologyValueId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of id
        <ColumnMapping("id")>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me._id = value
            End Set
        End Property
        
        'This is the property of ComponentId
        <ColumnMapping("ComponentId")>  _
        Public Property ComponentId() As Integer
            Get
                Return Me._ComponentId
            End Get
            Set
                Me._ComponentId = value
            End Set
        End Property
        
        'This is the property of MethodologyTypeId
        <ColumnMapping("MethodologyTypeId")>  _
        Public Property MethodologyTypeId() As Integer
            Get
                Return Me._MethodologyTypeId
            End Get
            Set
                Me._MethodologyTypeId = value
            End Set
        End Property
        
        'This is the property of MethodologyValueId
        <ColumnMapping("MethodologyValueId")>  _
        Public Property MethodologyValueId() As Integer
            Get
                Return Me._MethodologyValueId
            End Get
            Set
                Me._MethodologyValueId = value
            End Set
        End Property
    End Class
End Namespace
