'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class PMS_OperationCost
        
        Private _Id As Integer
        
        Private _TotalCost As Decimal?

        Private _SampleSize As Decimal?

        Private _AverageCostPerSample As Decimal?

        Private _CostDiff As Decimal?

        Private _CostName As String

        Private _CostType As String

        Private _CostingFileId As Integer

        Private _ComponentId As Integer

        Public Sub New()
            MyBase.New()
        End Sub

        'This is the property of Id
        <ColumnMapping("Id")> _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set(ByVal value As Integer)
                Me._Id = value
            End Set
        End Property

        'This is the property of TotalCost
        <ColumnMapping("TotalCost")> _
        Public Property TotalCost() As Decimal?
            Get
                Return Me._TotalCost
            End Get
            Set(ByVal value As Decimal?)
                Me._TotalCost = value
            End Set
        End Property

        'This is the property of SampleSize
        <ColumnMapping("SampleSize")> _
        Public Property SampleSize() As Decimal?
            Get
                Return Me._SampleSize
            End Get
            Set(ByVal value As Decimal?)
                Me._SampleSize = value
            End Set
        End Property

        'This is the property of AverageCostPerSample
        <ColumnMapping("AverageCostPerSample")> _
        Public Property AverageCostPerSample() As Decimal?
            Get
                Return Me._AverageCostPerSample
            End Get
            Set(ByVal value As Decimal?)
                Me._AverageCostPerSample = value
            End Set
        End Property

        'This is the property of CostDiff
        <ColumnMapping("CostDiff")> _
        Public Property CostDiff() As Decimal?
            Get
                Return Me._CostDiff
            End Get
            Set(ByVal value As Decimal?)
                Me._CostDiff = value
            End Set
        End Property

        'This is the property of CostName
        <ColumnMapping("CostName")> _
        Public Property CostName() As String
            Get
                Return Me._CostName
            End Get
            Set(ByVal value As String)
                Me._CostName = value
            End Set
        End Property

        'This is the property of CostType
        <ColumnMapping("CostType")> _
        Public Property CostType() As String
            Get
                Return Me._CostType
            End Get
            Set(ByVal value As String)
                Me._CostType = value
            End Set
        End Property

        'This is the property of CostingFileId
        <ColumnMapping("CostingFileId")> _
        Public Property CostingFileId() As Integer
            Get
                Return Me._CostingFileId
            End Get
            Set(ByVal value As Integer)
                Me._CostingFileId = value
            End Set
        End Property

        'This is the property of ComponentId
        <ColumnMapping("ComponentId")> _
        Public Property ComponentId() As Integer
            Get
                Return Me._ComponentId
            End Get
            Set(ByVal value As Integer)
                Me._ComponentId = value
            End Set
        End Property
        Public PropertyCellDictionary As New Dictionary(Of String, String)
        Private _EstimateCost As Decimal?
        ''' <summary>
        ''' This property is only used for showing
        ''' in dao file, if any object need be changed to PMS_OperationCost, need contain EstimateCost in sql script
        ''' </summary>
        ''' <value></value>
        ''' <returns></returns>
        ''' <remarks></remarks>
        <ColumnMapping("EstimateCost")> _
        Public Property EstimateCost() As Decimal?
            Get
                Return _EstimateCost
            End Get
            Set(ByVal value As Decimal?)
                _EstimateCost = value
            End Set
        End Property
    End Class
End Namespace
