'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class PMS_ProposalStage
        
        Private _Id As Integer
        
        Private _StageNumber As Integer
        
        Private _StageName As String

        Private _Description As String
        
        Private _CreatedBy As Integer
        
        Private _CreatedDate As Date?

        Private _UpdatedBy As Integer

        Private _UpdatedDate As Date?

        Private _Jobnumber As String

        Public Sub New()
            MyBase.New()
        End Sub

        'This is the property of Id
        <ColumnMapping("Id")> _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set(ByVal value As Integer)
                Me._Id = value
            End Set
        End Property

        'This is the property of StageNumber
        <ColumnMapping("StageNumber")> _
        Public Property StageNumber() As Integer
            Get
                Return Me._StageNumber
            End Get
            Set(ByVal value As Integer)
                Me._StageNumber = value
            End Set
        End Property

        'This is the property of StageName
        <ColumnMapping("StageName")> _
        Public Property StageName() As String
            Get
                Return Me._StageName
            End Get
            Set(ByVal value As String)
                Me._StageName = value
            End Set
        End Property


        'This is the property of StageName
        <ColumnMapping("Description")> _
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set(ByVal value As String)
                Me._Description = value
            End Set
        End Property

        'This is the property of CreatedBy
        <ColumnMapping("CreatedBy")> _
        Public Property CreatedBy() As Integer
            Get
                Return Me._CreatedBy
            End Get
            Set(ByVal value As Integer)
                Me._CreatedBy = value
            End Set
        End Property

        'This is the property of CreatedDate
        <ColumnMapping("CreatedDate")> _
        Public Property CreatedDate() As Date?
            Get
                Return Me._CreatedDate
            End Get
            Set(ByVal value As Date?)
                Me._CreatedDate = value
            End Set
        End Property

        'This is the property of UpdatedBy
        <ColumnMapping("UpdatedBy")> _
        Public Property UpdatedBy() As Integer
            Get
                Return Me._UpdatedBy
            End Get
            Set(ByVal value As Integer)
                Me._UpdatedBy = value
            End Set
        End Property

        'This is the property of UpdatedDate
        <ColumnMapping("UpdatedDate")> _
        Public Property UpdatedDate() As Date?
            Get
                Return Me._UpdatedDate
            End Get
            Set(ByVal value As Date?)
                Me._UpdatedDate = value
            End Set
        End Property
        
        'This is the property of Jobnumber
        <ColumnMapping("Jobnumber")>  _
        Public Property Jobnumber() As String
            Get
                Return Me._Jobnumber
            End Get
            Set
                Me._Jobnumber = value
            End Set
        End Property
    End Class
End Namespace
