'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports Utils

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class PMS_ComponentCostingFile
        
        Private _Id As Integer
        
        Private _ComponentId As Integer
        
        Private _ShowName As String
        
        Private _SaveName As String
        
        Private _UpdatedDate As Date?
        
        Private _UpdatedBy As Integer
        
        Private _CreatedDate As Date?
        
        Private _CreatedBy As Integer
        'Add on 2012/2/8
        Private _ShowName_Actual As String

        Private _SaveName_Actual As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of Id
        <ColumnMapping("Id")>  _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me._Id = value
            End Set
        End Property
        
        'This is the property of ComponentId
        <ColumnMapping("ComponentId")>  _
        Public Property ComponentId() As Integer
            Get
                Return Me._ComponentId
            End Get
            Set
                Me._ComponentId = value
            End Set
        End Property
        
        'This is the property of ShowName
        <ColumnMapping("ShowName")>  _
        Public Property ShowName() As String
            Get
                Return Me._ShowName
            End Get
            Set
                Me._ShowName = value
            End Set
        End Property
        
        'This is the property of SaveName
        <ColumnMapping("SaveName")>  _
        Public Property SaveName() As String
            Get
                Return Me._SaveName
            End Get
            Set
                Me._SaveName = value
            End Set
        End Property
        
        'This is the property of UpdatedDate
        <ColumnMapping("UpdatedDate")> _
        Public Property UpdatedDate() As Date?
            Get
                Return Me._UpdatedDate
            End Get
            Set(ByVal value As Date?)
                Me._UpdatedDate = Value
            End Set
        End Property
        
        'This is the property of UpdatedBy
        <ColumnMapping("UpdatedBy")>  _
        Public Property UpdatedBy() As Integer
            Get
                Return Me._UpdatedBy
            End Get
            Set
                Me._UpdatedBy = value
            End Set
        End Property
        
        'This is the property of CreatedDate
        <ColumnMapping("CreatedDate")> _
        Public Property CreatedDate() As Date?
            Get
                Return Me._CreatedDate
            End Get
            Set(ByVal value As Date?)
                Me._CreatedDate = Value
            End Set
        End Property
        
        'This is the property of CreatedBy
        <ColumnMapping("CreatedBy")>  _
        Public Property CreatedBy() As Integer
            Get
                Return Me._CreatedBy
            End Get
            Set
                Me._CreatedBy = value
            End Set
        End Property

        'This is the property of ShowName
        <ColumnMapping("ShowName_Actual")> _
        Public Property ShowName_Actual() As String
            Get
                Return Me._ShowName_Actual
            End Get
            Set(ByVal value As String)
                Me._ShowName_Actual = value
            End Set
        End Property

        'This is the property of SaveName
        <ColumnMapping("SaveName_Actual")> _
        Public Property SaveName_Actual() As String
            Get
                Return Me._SaveName_Actual
            End Get
            Set(ByVal value As String)
                Me._SaveName_Actual = value
            End Set
        End Property
    End Class
End Namespace
