'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class System_PermissionInfo
        
        Private _ID As Integer
        
        Private _Name As String
        
        Private _Description As String
        
        Private _Memo As String
        
        Private _Kind As Integer
        
        Private _PerLevel As Integer
        
        Private _ParentID As Integer
        
        Private _Sort As Integer
        
        Private _IsLink As Boolean
        
        Private _LinkURL As String
        
        Private _IsDeleted As Boolean
        
        Private _SystemModule As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of ID
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me._ID = value
            End Set
        End Property
        
        'This is the property of Name
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me._Name = value
            End Set
        End Property
        
        'This is the property of Description
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set
                Me._Description = value
            End Set
        End Property
        
        'This is the property of Memo
        Public Property Memo() As String
            Get
                Return Me._Memo
            End Get
            Set
                Me._Memo = value
            End Set
        End Property
        
        'This is the property of Kind
        Public Property Kind() As Integer
            Get
                Return Me._Kind
            End Get
            Set
                Me._Kind = value
            End Set
        End Property
        
        'This is the property of PerLevel
        Public Property PerLevel() As Integer
            Get
                Return Me._PerLevel
            End Get
            Set
                Me._PerLevel = value
            End Set
        End Property
        
        'This is the property of ParentID
        Public Property ParentID() As Integer
            Get
                Return Me._ParentID
            End Get
            Set
                Me._ParentID = value
            End Set
        End Property
        
        'This is the property of Sort
        Public Property Sort() As Integer
            Get
                Return Me._Sort
            End Get
            Set
                Me._Sort = value
            End Set
        End Property
        
        'This is the property of IsLink
        Public Property IsLink() As Boolean
            Get
                Return Me._IsLink
            End Get
            Set(ByVal value As Boolean)
                Me._IsLink = Value
            End Set
        End Property
        
        'This is the property of LinkURL
        Public Property LinkURL() As String
            Get
                Return Me._LinkURL
            End Get
            Set
                Me._LinkURL = value
            End Set
        End Property
        
        'This is the property of IsDeleted
        Public Property IsDeleted() As Boolean
            Get
                Return Me._IsDeleted
            End Get
            Set(ByVal value As Boolean)
                Me._IsDeleted = Value
            End Set
        End Property
        
        'This is the property of Module
        Public Property SystemModule() As String
            Get
                Return Me._SystemModule
            End Get
            Set(ByVal value As String)
                Me._SystemModule = value
            End Set
        End Property
    End Class
End Namespace
