'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data.SqlClient

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class System_UploadFile
        
        Private _UploadFileID As Integer
        
        Private _Comment As String

        Private _RelativePath As String

        Private _FileName As String
        
        Private _ReferModule As String
        
        Private _MainEntityID As Integer
        
        Private _CreatedBy As Integer
        
        Private _CreatedTime As String

        Private _identifyIdParam As SqlParameter

        Public Sub New()
            MyBase.New()
            _UploadFileID = 0
            _Comment = Nothing
            _RelativePath = Nothing
            _FileName = Nothing
            _ReferModule = Nothing
            _MainEntityID = 0
            _CreatedBy = 0
            _CreatedTime = DateTime.MinValue

        End Sub
        
        'This is the property of UploadFileID
        Public Property UploadFileID() As Integer
            Get
                Return Me._UploadFileID
            End Get
            Set
                Me._UploadFileID = value
            End Set
        End Property
        

        'This is the property of Comment
        Public Overloads Property Comment() As String
            Get
                Return Me._Comment
            End Get
            Set
                Me._Comment = value
            End Set
        End Property
        
      
        'This is the property of RelativePath
        Public Overloads Property RelativePath() As String
            Get
                Return Me._RelativePath
            End Get
            Set
                Me._RelativePath = value
            End Set
        End Property

        'This is the property of FileName
        Public Overloads Property FileName() As String
            Get
                Return Me._FileName
            End Get
            Set
                Me._FileName = value
            End Set
        End Property
        
        'This is the property of ReferModule
        Public Property ReferModule() As String
            Get
                Return Me._ReferModule
            End Get
            Set(ByVal value As String)
                Me._ReferModule = Value
            End Set
        End Property
        
        'This is the property of MainEntityID
        Public Property MainEntityID() As Integer
            Get
                Return Me._MainEntityID
            End Get
            Set
                Me._MainEntityID = value
            End Set
        End Property
        
        'This is the property of CreatedBy
        Public Property CreatedBy() As Integer
            Get
                Return Me._CreatedBy
            End Get
            Set
                Me._CreatedBy = value
            End Set
        End Property
        
        'This is the property of CreatedTime
        Public Property CreatedTime() As String
            Get
                Return Me._CreatedTime
            End Get
            Set
                Me._CreatedTime = value
            End Set
        End Property

        Public ReadOnly Property SqlScript_Insert As String
            Get
                Dim script As String
                script = "Insert into [t_System_UploadFile] ([Comment],[RelativePath],[FileName],ReferModule,MainEntityID,CreatedBy,CreatedTime) "
                script += "Values(@Comment,@RelativePath,@FileName,@ReferModule,@MainEntityID,@CreatedBy,@CreatedTime) "
                script += vbCrLf + "Select @IdentityId = @@identity  "
                Return script
            End Get
        End Property

        ''' <summary>
        ''' this propery can only be invoked after add a record to DB
        ''' when do the insert operation, as primary key is an identity,
        ''' So after execute insert script, we can use this property to get the New ID
        ''' </summary>
        ''' <value></value>
        ''' <returns></returns>
        ''' <remarks></remarks>
        Public ReadOnly Property NewIdentifyId As Integer
            Get
                If _identifyIdParam Is Nothing Then
                    Return 0
                End If
                Return Integer.Parse(_identifyIdParam.Value)
            End Get
        End Property

        Public Function GetSqlParameters() As SqlParameter()
            Dim paramList As New List(Of SqlParameter)
            Dim param As SqlParameter

            _identifyIdParam = New SqlParameter("@IdentityId", SqlDbType.Int)
            _identifyIdParam.Direction = ParameterDirection.Output
            paramList.Add(_identifyIdParam)

            param = New SqlParameter("@UploadFileId", SqlDbType.Int)
            If UploadFileID > 0 Then
                param.Value = UploadFileID
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@Comment", SqlDbType.NVarChar)
            If Comment IsNot Nothing Then
                param.Value = Comment
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@RelativePath", SqlDbType.NVarChar)
            If RelativePath IsNot Nothing Then
                param.Value = RelativePath
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@FileName", SqlDbType.NVarChar)
            If FileName IsNot Nothing Then
                param.Value = FileName
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@ReferModule", SqlDbType.NVarChar)
            If ReferModule IsNot Nothing Then
                param.Value = ReferModule
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@MainEntityID", SqlDbType.Int)
            If MainEntityID > 0 Then
                param.Value = MainEntityID
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@CreatedBy", SqlDbType.Int)
            If CreatedBy > 0 Then
                param.Value = CreatedBy
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            param = New SqlParameter("@CreatedTime", SqlDbType.DateTime)
            If CreatedTime <> DateTime.MinValue Then
                param.Value = CreatedTime
            Else
                param.Value = DBNull.Value
            End If
            paramList.Add(param)

            Return paramList.ToArray()

        End Function

    End Class
End Namespace
