'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class Wcf_BehaviorExtensionInfo
        
        Private _Id As Integer
        
        Private _ExtensionName As String
        
        Private _AppCode As String
        
        Private _SiteVersion As String
        
        Private _BehaviorType As String
        
        Private _BehaviorConfigurationElementType As String
        
        Private _ConfigVersion As String
        
        Private _InsertDate As String
        
        Private _InsertBy As String
        
        Private _UpdateDate As String
        
        Private _UpdateBy As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of Id
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me._Id = value
            End Set
        End Property
        
        'This is the property of ExtensionName
        Public Property ExtensionName() As String
            Get
                Return Me._ExtensionName
            End Get
            Set
                Me._ExtensionName = value
            End Set
        End Property
        
        'This is the property of AppCode
        Public Property AppCode() As String
            Get
                Return Me._AppCode
            End Get
            Set
                Me._AppCode = value
            End Set
        End Property
        
        'This is the property of SiteVersion
        Public Property SiteVersion() As String
            Get
                Return Me._SiteVersion
            End Get
            Set
                Me._SiteVersion = value
            End Set
        End Property
        
        'This is the property of BehaviorType
        Public Property BehaviorType() As String
            Get
                Return Me._BehaviorType
            End Get
            Set
                Me._BehaviorType = value
            End Set
        End Property
        
        'This is the property of BehaviorConfigurationElementType
        Public Property BehaviorConfigurationElementType() As String
            Get
                Return Me._BehaviorConfigurationElementType
            End Get
            Set
                Me._BehaviorConfigurationElementType = value
            End Set
        End Property
        
        'This is the property of ConfigVersion
        Public Property ConfigVersion() As String
            Get
                Return Me._ConfigVersion
            End Get
            Set
                Me._ConfigVersion = value
            End Set
        End Property
        
        'This is the property of InsertDate
        Public Property InsertDate() As String
            Get
                Return Me._InsertDate
            End Get
            Set
                Me._InsertDate = value
            End Set
        End Property
        
        'This is the property of InsertBy
        Public Property InsertBy() As String
            Get
                Return Me._InsertBy
            End Get
            Set
                Me._InsertBy = value
            End Set
        End Property
        
        'This is the property of UpdateDate
        Public Property UpdateDate() As String
            Get
                Return Me._UpdateDate
            End Get
            Set
                Me._UpdateDate = value
            End Set
        End Property
        
        'This is the property of UpdateBy
        Public Property UpdateBy() As String
            Get
                Return Me._UpdateBy
            End Get
            Set
                Me._UpdateBy = value
            End Set
        End Property
    End Class
End Namespace
