'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System

Namespace Model
    
    <System.SerializableAttribute()>  _
    Public Class WCF_ServiceInfo
        
        Private _Id As Integer
        
        Private _Service_id As Integer
        
        Private _SiteVersion As String
        
        Private _ServiceName As String
        
        Private _ServiceType As String
        
        Private _CustomServiceHostType As String
        
        Private _ServiceBehaviorXml As String
        
        Private _ServiceHostXml As String
        
        Private _InsertDate As DateTime
        
        Private _InsertBy As String
        
        Private _UpdateDate As DateTime
        
        Private _UpdateBy As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        'This is the property of Id
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me._Id = value
            End Set
        End Property
        
        'This is the property of Service_id
        Public Property Service_id() As Integer
            Get
                Return Me._Service_id
            End Get
            Set
                Me._Service_id = value
            End Set
        End Property
        
        'This is the property of SiteVersion
        Public Property SiteVersion() As String
            Get
                Return Me._SiteVersion
            End Get
            Set
                Me._SiteVersion = value
            End Set
        End Property
        
        'This is the property of ServiceName
        Public Property ServiceName() As String
            Get
                Return Me._ServiceName
            End Get
            Set
                Me._ServiceName = value
            End Set
        End Property
        
        'This is the property of ServiceType
        Public Property ServiceType() As String
            Get
                Return Me._ServiceType
            End Get
            Set
                Me._ServiceType = value
            End Set
        End Property
        
        'This is the property of CustomServiceHostType
        Public Property CustomServiceHostType() As String
            Get
                Return Me._CustomServiceHostType
            End Get
            Set
                Me._CustomServiceHostType = value
            End Set
        End Property
        
        'This is the property of ServiceBehaviorXml
        Public Property ServiceBehaviorXml() As String
            Get
                Return Me._ServiceBehaviorXml
            End Get
            Set
                Me._ServiceBehaviorXml = value
            End Set
        End Property
        
        'This is the property of ServiceHostXml
        Public Property ServiceHostXml() As String
            Get
                Return Me._ServiceHostXml
            End Get
            Set
                Me._ServiceHostXml = value
            End Set
        End Property
        
        'This is the property of InsertDate
        Public Property InsertDate() As DateTime
            Get
                Return Me._InsertDate
            End Get
            Set(ByVal value As DateTime)
                Me._InsertDate = Value
            End Set
        End Property
        
        'This is the property of InsertBy
        Public Property InsertBy() As String
            Get
                Return Me._InsertBy
            End Get
            Set
                Me._InsertBy = value
            End Set
        End Property
        
        'This is the property of UpdateDate
        Public Property UpdateDate() As DateTime
            Get
                Return Me._UpdateDate
            End Get
            Set(ByVal value As DateTime)
                Me._UpdateDate = Value
            End Set
        End Property
        
        'This is the property of UpdateBy
        Public Property UpdateBy() As String
            Get
                Return Me._UpdateBy
            End Get
            Set
                Me._UpdateBy = value
            End Set
        End Property
    End Class
End Namespace
