'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Model
Imports System
Imports System.Data
Imports System.Data.SqlClient

Namespace IDAL
    
    Friend Interface IBase_Message
        
        Function GetEntityById(ByVal Id As Integer) As Object
        
        Function GetEntityDataSet() As DataSet
        
        Sub DeleteEntity(ByVal Id As Integer)

        Function SaveMessage(ByVal message As Base_Message) As Integer
        Function GetUnremindMessage(ByVal userId As Integer) As DataSet
        Function SetMessageRead(ByVal messageId As Integer) As Boolean
        Function GetUserMessageList(ByVal userId As Integer) As DataSet
        Function GetMessageListByFilter(ByVal filter As MessageQueryFilter) As DataSet
        Function GetUserMessage(ByVal userId As Integer) As List(Of Base_Message)
        Sub SetReceiverMessageReaded(ByVal receiverId As Integer, ByVal messageId As Integer)
    End Interface
End Namespace
