'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Model
Imports System
Imports System.Data
Imports System.Data.SqlClient

Namespace IDAL
    
    Friend Interface IPMS_OperationCost
        
        Function GetEntityById(ByVal Id As Integer) As PMS_OperationCost
        
        Function GetEntityList() As List(Of PMS_OperationCost)
        
        Function GetEntityDataSet() As DataSet
        
        Sub DeleteEntity(ByVal Id As Integer)
        
        Function SaveEntity(ByVal entity As PMS_OperationCost) As Integer
        Function GetComponentCostList(ByVal costType As String, ByVal componentId As Integer) As List(Of PMS_OperationCost)
        Function GetProjectCostList(ByVal costType As String, ByVal jobNumber As String) As DataSet
        Function GetProjectAndCostDetail(ByVal costType As String, ByVal jobNumber As String) As DataSet
        Function GetProjectProfit(ByVal JobNumber As String, ByVal CostType As String) As List(Of PMS_OperationCost)

    End Interface
End Namespace
