'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Model
Imports System
Imports System.Data
Imports System.Data.SqlClient

Namespace IDAL
    
    Friend Interface IPMS_Quotation
        
        Function GetEntityById(ByVal Id As Integer) As PMS_Quotation
        
        Function GetEntityList() As List(Of PMS_Quotation)
        
        Function GetEntityDataSet() As DataSet
        
        Sub DeleteEntity(ByVal Id As Integer)
        
        Function SaveEntity(ByVal entity As PMS_Quotation) As Integer

        Function GetStageQuotation(ByVal stageId As Integer) As List(Of PMS_Quotation)

        Function GetProposalQuotationList(ByVal proposalId As Integer) As List(Of PMS_Quotation)

        Function GetQuotationListByJobNumber(ByVal jobNumber As String) As List(Of PMS_Quotation)

        Function GetInitQuotationListByMethodology(ByVal methodologyId As String) As List(Of PMS_Quotation)

        Function SaveQuotationList(ByVal quotationList As List(Of PMS_Quotation)) As Boolean

        Function SetQuotationListStatus(ByVal list As List(Of PMS_Quotation), ByVal status As String) As Boolean
        Function GetQuotationListByComponentId(ByVal componentId As String) As List(Of PMS_Quotation)
    End Interface
End Namespace
