'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Model
Imports System
Imports System.Data
Imports System.Data.SqlClient

Namespace IDAL
    
    Friend Interface IPMS_Component
        
        Function GetEntityById(ByVal Id As Integer) As PMS_Component
        
        Function GetEntityList() As List(Of PMS_Component)
        
        Function GetEntityDataSet() As DataSet
        
        Sub DeleteEntity(ByVal Id As Integer)
        
        Function SaveEntity(ByVal entity As PMS_Component) As Integer
        Function SaveComponent(ByVal entity As PMS_Component) As Integer
        Function GetStageComponentList(ByVal stageId As Integer) As List(Of PMS_Component)
    End Interface
End Namespace
