'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Model
Imports System
Imports System.Data
Imports System.Data.SqlClient

Namespace IDAL
    
    Friend Interface IWCF_Service
        
        Function GetEntityById(ByVal Id As Integer) As WCF_ServiceInfo
        
        Function GetEntityDataSet() As DataSet
        
        Sub DeleteEntityById(ByVal Id As Integer)

        Function GetAllWCFService() As List(Of WCF_ServiceInfo)

        Function GetWCFServiceByType(ByVal serviceType As String) As WCF_ServiceInfo

    End Interface
End Namespace
