'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text

Namespace SQLServerDAL
    
    Friend Class Base_MessageReceiverDAO
        Inherits BaseSqlServerDAO
        Implements IBase_MessageReceiver
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub
        
        Public Overridable Function GetEntityById(ByVal Id As Integer) As Object Implements IBase_MessageReceiver.GetEntityById
            Dim paramlevel As New SqlParameter("@DepID", SqlDbType.Int)
            paramlevel.Value = Id
            Dim sql As String = "select * from [t_Base_MessageReceiver] where ID = @ID "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql, paramlevel)
            If Not ds Is Nothing Then
              Return ds
            Else
              Return Nothing
            End If
        End Function
        
        Public Overridable Sub DeleteEntity(ByVal Id As Integer) Implements IBase_MessageReceiver.DeleteEntity
             Dim strSql As String = "delete from t_Base_MessageReceiver where id= @ID
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@ID"
            parameter.Value = Id
            Me.ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements IBase_MessageReceiver.GetEntityDataSet
            Dim sql As String = "select * from [t_Base_MessageReceiver] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function
    End Class
End Namespace
