'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text
Imports Utils

Namespace SQLServerDAL
    
    Friend Class PMS_MethodologyDAO
        Inherits BaseSqlServerDAO
        Implements IPMS_Methodology
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub
        
        Public Overridable Function SaveEntity(ByVal entity As PMS_Methodology) As Integer Implements IPMS_Methodology.SaveEntity
            Dim paramList As New List(Of SqlParameter)
            Dim id_parameter = New SqlParameter("@id", SqlDbType.Int)
            id_parameter.Value = entity.id
            paramList.Add(id_parameter)
            Dim ComponentId_parameter = New SqlParameter("@ComponentId", SqlDbType.Int)
            ComponentId_parameter.Value = entity.ComponentId
            paramList.Add(ComponentId_parameter)
            Dim MethodologyTypeId_parameter = New SqlParameter("@MethodologyTypeId", SqlDbType.Int)
            MethodologyTypeId_parameter.Value = entity.MethodologyTypeId
            paramList.Add(MethodologyTypeId_parameter)
            Dim MethodologyValueId_parameter = New SqlParameter("@MethodologyValueId", SqlDbType.Int)
            MethodologyValueId_parameter.Value = entity.MethodologyValueId
            paramList.Add(MethodologyValueId_parameter)
            Dim IdParameter = New SqlParameter("@id", SqlDbType.Int)
            If entity.id > 0 Then
              IdParameter.Value = entity.id
            Else
              IdParameter.Value = DBNull.Value
            End If
            Dim sql As String = ""
            Dim identityParameter As New SqlParameter("@IdentityId", SqlDbType.Int)
            If (entity.id = -1) Then
              identityParameter.Direction = ParameterDirection.Output
              paramList.Add(identityParameter)
                sql = "insert into t_PMS_Methodology(ComponentId,MethodologyTypeId,MethodologyValueId) "
               sql += "values(@ComponentId,@MethodologyTypeId,@MethodologyValueId) Select @IdentityId = @@identity  "
            Else
                paramList.Add(id_parameter)
                  sql = "update t_PMS_Methodology set ComponentId = @ComponentId,MethodologyTypeId = @MethodologyTypeId,MethodologyValueId = @MethodologyValueId where id =@id
            End If
            Dim count As Integer
            count = Me.ExecuteNonQuery(sql, paramList.ToArray())
            If (entity.id = -1) Then
              If Not identityParameter Is Nothing Then
                  entity.id = Integer.Parse(identityParameter.Value)
              End If
            End If
            Return count
        End Function
        
        Public Overridable Function GetEntityById(ByVal Id As Integer) As PMS_Methodology Implements IPMS_Methodology.GetEntityById
            Dim param As New SqlParameter("@id", SqlDbType.Int)
            param.Value = Id
            Dim strSQL As String = "select * from [t_PMS_Methodology] where id = @id "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL, param)
               If (dr.Read()) Then
                   Dim entity As New PMS_Methodology
                   ColumnMappingManage.MappingEntityByDataReader(Of PMS_Methodology)(entity, dr)
                   Return entity
               Else
                   Return Nothing
               End If
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        
        Public Overridable Sub DeleteEntity(ByVal id As Integer) Implements IPMS_Methodology.DeleteEntity
             Dim strSql As String = "delete from t_PMS_Methodology where id= @id
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@id"
            parameter.Value = id
            Me.ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements IPMS_Methodology.GetEntityDataSet
            Dim sql As String = "select * from [t_PMS_Methodology] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function
        
        Public Overridable Function GetEntityList() As List(Of PMS_Methodology) Implements IPMS_Methodology.GetEntityList
            Dim strSQL As String = "select * from [t_PMS_Methodology] "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL)
               Dim entityList As New List(Of PMS_Methodology)
               ColumnMappingManage.MappingListByDataReader(entityList, dr)
               Return entityList
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        Public Function GetMethodologyTypeDataSet() As DataSet Implements IPMS_Methodology.GetMethodologyTypeDataSet
            Dim strSQL = "select * from dbo.t_Base_Methodology_Type select * from dbo.t_Base_Methodology "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, strSQL)
            Return ds
        End Function
        Public Overridable Function GetComponentMethodlogy(ByVal componentId As Integer) As PMS_Methodology Implements IPMS_Methodology.GetComponentMethodlogy
            Dim strSQL As String = "select * from [t_PMS_Methodology] where componentid=" + componentId.ToString()
            Dim dr As SqlClient.SqlDataReader
            Try
                dr = Me.ExecuteReader(CommandType.Text, strSQL)
                Dim entityList As New List(Of PMS_Methodology)
                ColumnMappingManage.MappingListByDataReader(entityList, dr)
                If entityList.Count > 0 Then
                    Return entityList(0)
                End If
                Return Nothing
            Catch ex As Exception
                Return Nothing
            Finally
                If (Not dr.IsClosed) Then
                    dr.Close()
                End If
            End Try
        End Function

    End Class
End Namespace
