'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text
Imports Utils

Namespace SQLServerDAL
    
    Friend Class PMS_ProjectRevenueDAO
        Inherits BaseSqlServerDAO
        Implements IPMS_ProjectRevenue
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub
        
        Public Overridable Function SaveEntity(ByVal entity As PMS_ProjectRevenue) As Integer Implements IPMS_ProjectRevenue.SaveEntity
            Dim paramList As New List(Of SqlParameter)
            Dim Id_parameter = New SqlParameter("@Id", SqlDbType.Int)
            If entity.Id > 0 Then
              Id_parameter.Value = entity.Id
            Else
              Id_parameter.Value = DBNull.Value
            End If
            Dim ProjectId_parameter = New SqlParameter("@ProjectId", SqlDbType.Int)
            ProjectId_parameter.Value = entity.ProjectId
            paramList.Add(ProjectId_parameter)
            Dim JobNumber_parameter As New SqlParameter("@JobNumber", SqlDbType.NVarChar, 50)
            JobNumber_parameter.Value = entity.JobNumber
            paramList.Add(JobNumber_parameter)
            Dim CostName_parameter As New SqlParameter("@CostName", SqlDbType.NVarChar, 100)
            CostName_parameter.Value = entity.CostName
            paramList.Add(CostName_parameter)
            Dim CostValue_parameter As New SqlParameter("@CostValue", SqlDbType.NVarChar, 9)
            CostValue_parameter.Value = entity.CostValue
            paramList.Add(CostValue_parameter)
            Dim sql As String = ""
            Dim identityParameter As New SqlParameter("@IdentityId", SqlDbType.Int)
            If (entity.id = -1) Then
              identityParameter.Direction = ParameterDirection.Output
              paramList.Add(identityParameter)
                sql = "insert into t_PMS_ProjectRevenue(ProjectId,JobNumber,CostName,CostValue) "
               sql += "values(@ProjectId,@JobNumber,@CostName,@CostValue) Select @IdentityId = @@identity  "
            Else
            paramList.Add(Id_parameter)
                  sql = "update t_PMS_ProjectRevenue set ProjectId = @ProjectId,JobNumber = @JobNumber,CostName = @CostName,CostValue = @CostValue where Id =@Id
            End If
            Dim count As Integer
            count = Me.ExecuteNonQuery(sql, paramList.ToArray())
            If (entity.Id = -1) Then
              If Not identityParameter Is Nothing Then
                  entity.Id = Integer.Parse(identityParameter.Value)
              End If
            End If
            Return count
        End Function
        
        Public Overridable Function GetEntityById(ByVal Id As Integer) As PMS_ProjectRevenue Implements IPMS_ProjectRevenue.GetEntityById
            Dim param As New SqlParameter("@Id", SqlDbType.Int)
            param.Value = Id
            Dim strSQL As String = "select * from [t_PMS_ProjectRevenue] where Id = @Id "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL, param)
               If (dr.Read()) Then
                   Dim entity As New PMS_ProjectRevenue
                   ColumnMappingManage.MappingEntityByDataReader(Of PMS_ProjectRevenue)(entity, dr)
                   Return entity
               Else
                   Return Nothing
               End If
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        
        Public Overridable Sub DeleteEntity(ByVal Id As Integer) Implements IPMS_ProjectRevenue.DeleteEntity
             Dim strSql As String = "delete from t_PMS_ProjectRevenue where Id= @Id
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@Id"
            parameter.Value = Id
            Me.ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements IPMS_ProjectRevenue.GetEntityDataSet
            Dim sql As String = "select * from [t_PMS_ProjectRevenue] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function
        
        Public Overridable Function GetEntityList() As List(Of PMS_ProjectRevenue) Implements IPMS_ProjectRevenue.GetEntityList
            Dim strSQL As String = "select * from [t_PMS_ProjectRevenue] "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL)
               Dim entityList As New List(Of PMS_ProjectRevenue)
               ColumnMappingManage.MappingListByDataReader(entityList, dr)
               Return entityList
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        Public Overridable Function GetProjectRevenueList(ByVal jobNumber As String, ByVal projectId As String) As List(Of PMS_ProjectRevenue) Implements IPMS_ProjectRevenue.GetProjectRevenueList
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@JobNumber"
            parameter.Value = jobNumber
            Dim strSQL As String = "select * from [t_PMS_ProjectRevenue] where JobNumber = @JobNumber"
            Dim dr As SqlClient.SqlDataReader
            Try
                dr = Me.ExecuteReader(CommandType.Text, strSQL, parameter)
                Dim entityList As New List(Of PMS_ProjectRevenue)
                ColumnMappingManage.MappingListByDataReader(entityList, dr)
                Return entityList
            Catch ex As Exception
                Return Nothing
            Finally
                If (Not dr.IsClosed) Then
                    dr.Close()
                End If
            End Try
        End Function
    End Class
End Namespace
