'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text
Imports Utils

Namespace SQLServerDAL
    
    Friend Class PMS_ComponentCostingFileDAO
        Inherits BaseSqlServerDAO
        Implements IPMS_ComponentCostingFile
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub
        
        Public Overridable Function SaveEntity(ByVal entity As PMS_ComponentCostingFile) As Integer Implements IPMS_ComponentCostingFile.SaveEntity
            Dim paramList As New List(Of SqlParameter)
            Dim Id_parameter = New SqlParameter("@Id", SqlDbType.Int)
            If entity.Id > 0 Then
              Id_parameter.Value = entity.Id
            Else
              Id_parameter.Value = DBNull.Value
            End If
            Dim ComponentId_parameter = New SqlParameter("@ComponentId", SqlDbType.Int)
            ComponentId_parameter.Value = entity.ComponentId
            paramList.Add(ComponentId_parameter)
            Dim ShowName_parameter As New SqlParameter("@ShowName", SqlDbType.NVarChar, 150)
            ShowName_parameter.Value = entity.ShowName
            paramList.Add(ShowName_parameter)
            Dim SaveName_parameter As New SqlParameter("@SaveName", SqlDbType.NVarChar, 150)
            SaveName_parameter.Value = entity.SaveName
            paramList.Add(SaveName_parameter)
            Dim UpdatedDate_parameter = New SqlParameter("@UpdatedDate", SqlDbType.DateTime)
            UpdatedDate_parameter.Value = entity.UpdatedDate
            paramList.Add(UpdatedDate_parameter)
            Dim UpdatedBy_parameter = New SqlParameter("@UpdatedBy", SqlDbType.Int)
            UpdatedBy_parameter.Value = entity.UpdatedBy
            paramList.Add(UpdatedBy_parameter)
            Dim CreatedDate_parameter = New SqlParameter("@CreatedDate", SqlDbType.DateTime)
            CreatedDate_parameter.Value = entity.CreatedDate
            paramList.Add(CreatedDate_parameter)
            Dim CreatedBy_parameter = New SqlParameter("@CreatedBy", SqlDbType.Int)
            CreatedBy_parameter.Value = entity.CreatedBy
            paramList.Add(CreatedBy_parameter)
            Dim sql As String = ""
            Dim identityParameter As New SqlParameter("@IdentityId", SqlDbType.Int)
            If (entity.id = -1) Then
              identityParameter.Direction = ParameterDirection.Output
              paramList.Add(identityParameter)
                sql = "insert into t_PMS_ComponentCostingFile(ComponentId,ShowName,SaveName,UpdatedDate,UpdatedBy,CreatedDate,CreatedBy) "
               sql += "values(@ComponentId,@ShowName,@SaveName,@UpdatedDate,@UpdatedBy,@CreatedDate,@CreatedBy) Select @IdentityId = @@identity  "
            Else
            paramList.Add(Id_parameter)
                  sql = "update t_PMS_ComponentCostingFile set ComponentId = @ComponentId,ShowName = @ShowName,SaveName = @SaveName,UpdatedDate = @UpdatedDate,UpdatedBy = @UpdatedBy,CreatedDate = @CreatedDate,CreatedBy = @CreatedBy where Id =@Id
            End If
            Dim count As Integer
            count = Me.ExecuteNonQuery(sql, paramList.ToArray())
            If (entity.Id = -1) Then
              If Not identityParameter Is Nothing Then
                  entity.Id = Integer.Parse(identityParameter.Value)
              End If
            End If
            Return count
        End Function
        
        Public Overridable Function GetEntityById(ByVal Id As Integer) As PMS_ComponentCostingFile Implements IPMS_ComponentCostingFile.GetEntityById
            Dim param As New SqlParameter("@Id", SqlDbType.Int)
            param.Value = Id
            Dim strSQL As String = "select * from [t_PMS_ComponentCostingFile] where Id = @Id "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL, param)
               If (dr.Read()) Then
                   Dim entity As New PMS_ComponentCostingFile
                   ColumnMappingManage.MappingEntityByDataReader(Of PMS_ComponentCostingFile)(entity, dr)
                   Return entity
               Else
                   Return Nothing
               End If
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        
        Public Overridable Sub DeleteEntity(ByVal Id As Integer) Implements IPMS_ComponentCostingFile.DeleteEntity
             Dim strSql As String = "delete from t_PMS_ComponentCostingFile where Id= @Id
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@Id"
            parameter.Value = Id
            Me.ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements IPMS_ComponentCostingFile.GetEntityDataSet
            Dim sql As String = "select * from [t_PMS_ComponentCostingFile] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function
        
        Public Overridable Function GetEntityList() As List(Of PMS_ComponentCostingFile) Implements IPMS_ComponentCostingFile.GetEntityList
            Dim strSQL As String = "select * from [t_PMS_ComponentCostingFile] "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL)
               Dim entityList As New List(Of PMS_ComponentCostingFile)
               ColumnMappingManage.MappingListByDataReader(entityList, dr)
               Return entityList
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        ''' <summary>
        ''' This method is used to get the costing file of component.
        ''' </summary>
        ''' <param name="componentId">Pass the component id.</param>
        ''' <returns>Return costing file list.</returns>
        ''' <remarks></remarks>
        Public Overridable Function GetComponentCostingFile(ByVal componentId As Integer) As List(Of PMS_ComponentCostingFile) Implements IPMS_ComponentCostingFile.GetComponentCostingFile
            Dim strSQL As String = "select * from [t_PMS_ComponentCostingFile] where componentId=@ComponentId"

            Dim dr As SqlClient.SqlDataReader
            Try
                Dim parameter As New SqlParameter
                parameter.ParameterName = "@ComponentId"
                parameter.Value = componentId
                dr = Me.ExecuteReader(CommandType.Text, strSQL, parameter)
                Dim entityList As New List(Of PMS_ComponentCostingFile)
                ColumnMappingManage.MappingListByDataReader(entityList, dr)
                Return entityList
            Catch ex As Exception
                Return Nothing
            Finally
                If (Not dr.IsClosed) Then
                    dr.Close()
                End If
            End Try
        End Function
    End Class
End Namespace
