'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text
Imports Utils

Namespace SQLServerDAL
    
    Friend Class PMS_CityCoverageDAO
        Inherits BaseSqlServerDAO
        Implements IPMS_CityCoverage
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub
        
        Public Overridable Function SaveEntity(ByVal entity As PMS_CityCoverage) As Integer Implements IPMS_CityCoverage.SaveEntity
            Dim paramList As New List(Of SqlParameter)
            Dim id_parameter = New SqlParameter("@id", SqlDbType.Int)
            If entity.id > 0 Then
              id_parameter.Value = entity.id
            Else
              id_parameter.Value = DBNull.Value
            End If
            Dim ComponentId_parameter = New SqlParameter("@ComponentId", SqlDbType.Int)
            ComponentId_parameter.Value = entity.ComponentId
            paramList.Add(ComponentId_parameter)
            Dim District_parameter = New SqlParameter("@District", SqlDbType.Int)
            District_parameter.Value = entity.District
            paramList.Add(District_parameter)
            Dim Province_parameter = New SqlParameter("@Province", SqlDbType.Int)
            Province_parameter.Value = entity.Province
            paramList.Add(Province_parameter)
            Dim City_parameter = New SqlParameter("@City", SqlDbType.Int)
            City_parameter.Value = entity.City
            paramList.Add(City_parameter)
            Dim CitySize_parameter = New SqlParameter("@CitySize", SqlDbType.Decimal)
            CitySize_parameter.Value = entity.CitySize
            paramList.Add(CitySize_parameter)
            Dim AddedSize_parameter = New SqlParameter("@AddedSize", SqlDbType.Decimal)
            AddedSize_parameter.Value = entity.AddedSize
            paramList.Add(AddedSize_parameter)
            Dim IncidenceRate_parameter = New SqlParameter("@IncidenceRate", SqlDbType.Int)
            IncidenceRate_parameter.Value = entity.IncidenceRate
            paramList.Add(IncidenceRate_parameter)
            Dim sql As String = ""
            Dim identityParameter As New SqlParameter("@IdentityId", SqlDbType.Int)
            If (entity.id = -1) Then
              identityParameter.Direction = ParameterDirection.Output
              paramList.Add(identityParameter)
                sql = "insert into t_PMS_CityCoverage(ComponentId,District,Province,City,CitySize,AddedSize,IncidenceRate) "
               sql += "values(@ComponentId,@District,@Province,@City,@CitySize,@AddedSize,@IncidenceRate) Select @IdentityId = @@identity  "
            Else
            paramList.Add(id_parameter)
                  sql = "update t_PMS_CityCoverage set ComponentId = @ComponentId,District = @District,Province = @Province,City = @City,CitySize = @CitySize,AddedSize = @AddedSize,IncidenceRate = @IncidenceRate where id =@id
            End If
            Dim count As Integer
            count = Me.ExecuteNonQuery(sql, paramList.ToArray())
            If (entity.id = -1) Then
              If Not identityParameter Is Nothing Then
                  entity.id = Integer.Parse(identityParameter.Value)
              End If
            End If
            Return count
        End Function
        
        Public Overridable Function GetEntityById(ByVal Id As Integer) As PMS_CityCoverage Implements IPMS_CityCoverage.GetEntityById
            Dim param As New SqlParameter("@id", SqlDbType.Int)
            param.Value = Id
            Dim strSQL As String = "select * from [t_PMS_CityCoverage] where id = @id "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL, param)
               If (dr.Read()) Then
                   Dim entity As New PMS_CityCoverage
                   ColumnMappingManage.MappingEntityByDataReader(Of PMS_CityCoverage)(entity, dr)
                   Return entity
               Else
                   Return Nothing
               End If
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        
        Public Overridable Sub DeleteEntity(ByVal id As Integer) Implements IPMS_CityCoverage.DeleteEntity
             Dim strSql As String = "delete from t_PMS_CityCoverage where id= @id
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@id"
            parameter.Value = id
            Me.ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements IPMS_CityCoverage.GetEntityDataSet
            Dim sql As String = "select * from [t_PMS_CityCoverage] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function
        
        Public Overridable Function GetEntityList() As List(Of PMS_CityCoverage) Implements IPMS_CityCoverage.GetEntityList
            Dim strSQL As String = "select * from [t_PMS_CityCoverage] "
            Dim dr As SqlClient.SqlDataReader
            Try
               dr = Me.ExecuteReader(CommandType.Text, strSQL)
               Dim entityList As New List(Of PMS_CityCoverage)
               ColumnMappingManage.MappingListByDataReader(entityList, dr)
               Return entityList
            Catch ex As Exception
               Return Nothing
            Finally
               If (Not dr.IsClosed) Then
                   dr.Close()
               End If
            End Try
        End Function
        Public Overridable Function GetComponentCityCoverageList(ByVal componentId As Integer) As List(Of PMS_CityCoverage) Implements IPMS_CityCoverage.GetComponentCityCoverageList
            Dim strSQL As String = "select * from [t_PMS_CityCoverage]  where componentId = " + componentId.ToString()
            Dim dr As SqlClient.SqlDataReader
            Try
                dr = Me.ExecuteReader(CommandType.Text, strSQL)
                Dim entityList As New List(Of PMS_CityCoverage)
                ColumnMappingManage.MappingListByDataReader(entityList, dr)
                Return entityList
            Catch ex As Exception
                Return Nothing
            Finally
                If (Not dr.IsClosed) Then
                    dr.Close()
                End If
            End Try
        End Function

    End Class
End Namespace
