'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports DataAccess.Components
Imports DataAccess.IDAL
Imports DataAccess.Model
Imports Microsoft.ApplicationBlocks.Data
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Text

Namespace SQLServerDAL
    
    Friend Class System_UploadFileDAO
        Inherits BaseSqlServerDAO
        Implements ISystem_UploadFile
        
        Public Sub New(ByVal factory As SqlServerFactory)
            MyBase.New(factory)
        End Sub

        Public Function AddEntity(ByVal entity As System_UploadFile) As Integer Implements ISystem_UploadFile.AddEntity
            ExecuteNonQuery(entity.SqlScript_Insert, entity.GetSqlParameters())
            Return entity.NewIdentifyId
        End Function

        Public Function GetUploadFileIdListByMainEntityId(ByVal mainEntityId As Integer) As List(Of Integer) Implements ISystem_UploadFile.GetUploadFileIdListByMainEntityId
            Dim strSql As String
            strSql = "select UploadFileID from t_system_uploadFile where MainEntityId = " + mainEntityId.ToString()
            Dim dsResult As DataSet = ExecuteDataSet(strSql)
            Dim idList As List(Of Integer) = Nothing
            If dsResult IsNot Nothing AndAlso dsResult.Tables(0).Rows.Count > 0 Then
                idList = New List(Of Integer)
                For Each dr As DataRow In dsResult.Tables(0).Rows
                    idList.Add(Integer.Parse(dr("UploadFileID")))
                Next
            End If

            Return idList
        End Function

        Public Overridable Function GetEntityById(ByVal Id As Integer) As System_UploadFile Implements ISystem_UploadFile.GetEntityById
            Dim paramlevel As New SqlParameter("@UploadFileID", SqlDbType.Int)
            paramlevel.Value = Id
            Dim sql As String = "select * from [t_System_UploadFile] where UploadFileID = @UploadFileID "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql, paramlevel)
            If Not ds Is Nothing AndAlso ds.Tables(0).Rows.Count > 0 Then
                Return MapRowToEntity(ds.Tables(0).Rows(0))
            Else
                Return Nothing
            End If
        End Function
        
        Public Overridable Sub DeleteEntityById(ByVal Id As Integer) Implements ISystem_UploadFile.DeleteEntityById
            Dim strSql As String = "delete from t_System_UploadFile where UploadFileID= @UploadFileID"
            Dim parameter As New SqlParameter
            parameter.ParameterName = "@UploadFileID"
            parameter.Value = Id
            ExecuteNonQuery(strSql, parameter)
        End Sub
        
        Public Overridable Function GetEntityDataSet() As Dataset Implements ISystem_UploadFile.GetEntityDataSet
            Dim sql As String = "select * from [t_System_UploadFile] "
            Dim ds As DataSet = Me.ExecuteDataSet(CommandType.Text, sql)
            Return ds
        End Function

        Public Function UpdateFileMainEntityId(ByVal fileIdList As List(Of Integer), ByVal mainEntityID As Integer) As Boolean Implements ISystem_UploadFile.UpdateFileMainEntityId
            Dim sql As String
            If fileIdList Is Nothing OrElse fileIdList.Count = 0 Then
                Return False
            End If
            Dim strIds As String = String.Empty
            For Each id As Integer In fileIdList
                strIds += id.ToString() + ","
            Next
            strIds = strIds.Substring(0, strIds.Length - 1)
            sql = "update t_System_UploadFile set MainEntityID = " + mainEntityID.ToString() + " where UploadFileID in (" + strIds + ")"

            Return ExecuteNonQuery(sql) > 0

        End Function

        Public Function MapRowToEntity(ByVal dr As DataRow) As System_UploadFile
            Dim entity As New System_UploadFile
            entity.UploadFileID = Convert.ToInt32(dr("UploadFileID"))
            entity.RelativePath = Convert.ToString(dr("RelativePath"))
            entity.FileName = Convert.ToString(dr("FileName"))

            If Not Convert.IsDBNull(dr("Comment")) Then
                entity.Comment = Convert.ToString(dr("Comment"))
            End If

            If Not Convert.IsDBNull(dr("ReferModule")) Then
                entity.ReferModule = Convert.ToString(dr("ReferModule"))
            End If

            If Not Convert.IsDBNull(dr("MainEntityID")) Then
                entity.MainEntityID = Convert.ToInt32(dr("MainEntityID"))
            End If

            If Not Convert.IsDBNull(dr("CreatedBy")) Then
                entity.CreatedBy = Convert.ToInt32(dr("ModifiedBy"))
            End If

            If Not Convert.IsDBNull(dr("CreatedTime")) Then
                entity.CreatedTime = Convert.ToDateTime(dr("CreatedTime"))
            End If

            Return entity
        End Function

    End Class
End Namespace
